config/routes.rb
Rails.application.routes.draw do
  get "people/index"
  resource :session
  resources :passwords, param: :token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.

  root "animals#index"
  get "up" => "rails/health#show", as: :rails_health_check
  
  resources :animals #do 
#      resources :animal_vitals
#  end
  resources :people
#  resources :animal_vitals do 
#    resources :animals
#  end
  resources :vitals
  post "/animal_vitals/animal/:id",         to: "animal_vitals#create", as: "animal_vital"
  get  "/animal_vitals/new/animal/:id",     to: "animal_vitals#new",    as: "new_animal_vital"
  get  "/animal_vitals/:id",                to: "animal_vitals#edit", as: "edit_animal_vital"

get    "/animal_vitals/animal/:id", to: "animal_vitals#index",   as: "animal_vitals"
patch  "/animal_vitals/:id",        to: "animal_vitals#update",  as: "update_animal_vital"
put    "/animal_vitals/:id",        to: "animal_vitals#update"
delete "/animal_vitals/:id",        to: "animal_vitals#destroy", as: "delete_animal_vital"

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
end

app/models/animal.rb
class Animal < ApplicationRecord

  belongs_to :microchip, optional: true
  belongs_to :gender, optional: true
  belongs_to :species
  belongs_to :status, optional: true

  has_many :transfers
  has_many :vitals
  has_many :animal_personalities, dependent: :destroy
  has_many :personalities, through: :animal_personalities

  has_many :animal_vitals, dependent: :destroy
  has_many :vitals, through: :animal_vitals

  has_one_attached :photo do |attachable|
	attachable.variant :thumb, resize_to_limit: [50, 50]
  end

  validates :name, :species, presence: true
  before_save :normalize_blank_values
  
  def normalize_blank_values
    attributes.each do |column, value|
      self[column] = nil if value.blank? && value != false
    end
  end
end

app/models/animal_attribute.rb
class AnimalAttribute < ApplicationRecord
  belongs_to :animal
  belongs_to :pattribute
end

app/models/animal_personality.rb
class AnimalPersonality < ApplicationRecord
	belongs_to :animal
	belongs_to :personality
end

app/models/animal_vital.rb
class AnimalVital < ApplicationRecord
	belongs_to :animal
	belongs_to :vital


  def normalize_blank_values
    attributes.each do |column, value|
      self[column] = nil if value.blank? && value != false
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attribute.rb
class Attribute < ApplicationRecord
  has_many :animal_attributes, dependent: :destroy
  has_many :animmals, through: :animal_attributes
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :session
  delegate :user, to: :session, allow_nil: true
end

app/models/gender.rb
class Gender < ApplicationRecord
  has_many :animals
end

app/models/microchip.rb
class Microchip < ApplicationRecord
	has_many :animals
end

app/models/microchip_type.rb
class MicrochipType < ApplicationRecord
	has_many :animal
end

app/models/person.rb
class Person < ApplicationRecord

  def normalize_blank_values
    attributes.each do |column, value|
      self[column] = nil if value.blank? && value != false
    end
  end

end

app/models/personality.rb
class Personality < ApplicationRecord
  has_many :animal_personalities, dependent: :destroy
  has_many :animals, through: :animal_personality

end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
end

app/models/species.rb
class Species < ApplicationRecord
	has_many :animals
	has_many :vitals
end

app/models/status.rb
class Status < ApplicationRecord
	has_many :animals
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :sessions, dependent: :destroy

  normalizes :email_address, with: ->(e) { e.strip.downcase }
end

app/models/vital.rb
class Vital < ApplicationRecord
  has_many :animal_vitals, dependent: :destroy
  has_many :animals, through: :animal_vital
  belongs_to :species, optional: true
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  allow_unauthenticated_access only: %i[ index show ]
  before_action :set_animal, only: %i[ show edit update destroy ]
  def index
	@animals = Animal.all
  end

  def show
    @pageName = "View Animal"
    @gender =    @animal.species_id != nil ? Gender.find(@animal.genders_id).name : ""
    @species =    @animal.species_id != nil ? Species.find(@animal.species_id).name : ""
    @microchip =  @animal.microchips_id != nil ? Microchip.find(@animal.microchips_id).name : ""
    @status =     @animal.statuses_id != nil ? Status.find(@animal.statuses_id).name : ""
    @animal_vitals = AnimalVital.where(animal_id: @animal.id)
  end

  def new
    @pageName = "New Animal"
    @animal = Animal.new
  end

  def create
    @pageName = "Add Animal"
    @animal = Animal.new(animal_params)
#    @animal.photo.attach(params[:photo])
    if @animal.save!
      redirect_to @animal
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @pageName = "Edit Animal"
  end

  def update
#    Rails.error.subscribe(ErrorSubscriber.new)
    if @animal.update!(animal_params)
      @animal.photo.attach(params[:photo])
      redirect_to @animal
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
      @animal.destroy
      redirect_to animals_path
  end

  private
    def set_animal
      @animal = Animal.find(params[:id])
    end

    def animal_params
      params.expect(animal: [ :name, :species_id, :dob,  :genders_id, :breed, :markings, :microchipNumber, :dateImplanted, :dogs, :cats, :kids, :note, :isHypo, :isFixed, :microchips_id, :statuses_id, :photo, personality_ids: [] ])
    end
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/vital_helper.rb
module VitalHelper
end

app/helpers/vitals_helper.rb
module VitalsHelper
end

app/views/animals/_form.html.erb
<%= form_with model: @animal do |form| %>
  <div>
<table id=criteria>
                <tr>
                        <td>    <!-- Column 1 -->
                                <table > <!-- first column of demographic information -->
                                        <tr><td><%= form.label :name %></td><td><%= form.text_field :name %></tr>
                                        <tr>
                                                <td style="text-align: right;">Gender: </td>
                                                <td style="text-align: left;" ><%= form.collection_select(:genders_id, Gender.all, :id, :name, selected: @animal.genders_id) %></td>
                                        </tr>

                                        <tr><td>Neutered / Spayed?</td><td>
                                                                                <%= form.label :isFixed, 'Yes' %><%= form.radio_button :isFixed, true %><br>
                                                                                <%= form.label :isFixed, 'No' %><%= form.radio_button :isFixed, false %>
                                        </td></tr>



                                        <tr><td><%= form.label :dob, "Birthdate" %></td><td><%= form.date_field :dob %></tr>
                                        <tr>
                                                <td></td>
                                                <td style="text-align: left;" >
                                                        Or: <input type="txt" size=7 name="estbirthdateNumber">
                                                        <select name="estbirthdateInterval">
                                                                        <option value="D">Days</option>
                                                                        <option value="W">Weeks</option>
                                                                        <option value="M">Months</option>
                                                                        <option value="Y">Years</option>
                                                        </select>
                                                </td>
                                        </tr>
                                        <tr>
                                                <td style="text-align: right;"><b>Species*</b> </td>
                                                <td style="text-align: left;" ><%= form.collection_select(:species_id, Species.all, :id, :name,  selected: @animal.species_id) %></td>
                                        </tr>
                                        <tr><td><%= form.label :breed, "Breed" %></td><td><%= form.text_field :breed %></tr>
                                        <tr><td><%= form.label :breed, "Markings" %></td><td><%= form.text_field :markings %></tr>
                                        <tr><td>Personality</td><td><%= form.collection_check_boxes :personality_ids, Personality.all, :id, :name do |p| %>
  								<%= p.label { p.check_box + p.text } %><br>
								<% end %></td></tr>
                </table>
                      </td>
                        <td>    <!-- Column 2 -->
                                <table>
                                        <tr><td><%= form.label :microchipNumber, "Microchip #" %></td><td><%= form.text_field :microchipNumber %></tr>
                                        <tr><td><%= form.label :dateImplanted, "Date Implanted" %></td><td><%= form.date_field :dateImplanted %></tr>
                                        <tr><td><%= form.label :microchip_id, "Manufactuer" %></td><td><%= form.collection_select(:microchips_id, Microchip.all, :id, :name, prompt: true, selected: @animal.microchips_id) %></td></tr>
                                        <tr><td><%= form.label :dogs, "Good with dogs?" %></td><td>
                                                                                <%= form.label :dogs, 'Yes' %><%= form.radio_button :dogs, true %><br>
                                                                                <%= form.label :dogs, 'No' %><%= form.radio_button :dogs, false %><br>
                                                                                <%= form.label :dogs, 'Unsure' %><%= form.radio_button :dogs, '' %>
                                        </td></tr>
                                        <tr><td><%= form.label :cats, "Good with cats?" %></td><td>
                                                                                <%= form.label :cats, 'Yes' %><%= form.radio_button :cats, true %><br>
                                                                                <%= form.label :cats, 'No' %><%= form.radio_button :cats, false %><br>
                                                                                <%= form.label :cats, 'Unsure' %><%= form.radio_button :cats, '' %>
                                        </td></tr>
                                        <tr><td><%= form.label :kids, "Good with kids?" %></td><td>
                                                                                <%= form.label :kids, 'Yes' %><%= form.radio_button :kids, true %><br>
                                                                                <%= form.label :kids, 'No' %><%= form.radio_button :kids, false %><br>
                                                                                <%= form.label :kids, 'Unsure' %><%= form.radio_button :kids, '' %>
                                        </td></tr>
                                        <tr><td>Adoption Status</td><td style="text-align: left;" ><%= form.collection_select(:statuses_id, Status.all, :id, :name,  prompt: true, selected: @animal.statuses_id) %></td></tr>

                                </table>
                        </td>
                        <td>    <!-- Column 3 -->
                                <table>
                                <tr><td><%= form.file_field :photo %></td></tr>
				</table>
                        </td>
                </tr>
                <tr>
                        <td colspan="3"><%= form.label :note, "Note" %></td><td><%= form.text_field :note %>
                        </td>
                </tr>
        </table>


  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/animals/edit.html.erb
<h1>Edit <%= link_to @animal.name, @animal %></h1>

<%= render "form", animal: @animal %>
<%= button_to "Delete", @animal, method: :delete, data: { turbo_confirm: "Are you sure?" } %>
<%= link_to "Cancel", @animal %>

app/views/animals/index.html.erb
<h1>Animals</h1>

<div id="animals">
  <% @animals.each do |animal| %>
    <div>
	<%= link_to animal.name, animal %>
    </div>
  <% end %>
</div>

<%= link_to "Add Animal", new_animal_path %>

app/views/animals/new.html.erb
<h1>New animal</h1>

<%= render "form", animal: @animal %>
<%= link_to "Cancel", animals_path %>

app/views/animals/show.html.erb
<h1><%= link_to @animal.name, @animal %></h1>


<table  width=100%>  
        <tr> <!-- Animal demographic information -->
                <td>
                        <table id="criteria"> 
				<tr><td id="leftHand">Name</td><td id="rightHand"><%= @animal.name %></td></tr>
                                <tr><td id="leftHand">Gender</td><td id="rightHand"><%= @gender %></td></tr>
                                <tr><td id="leftHand">Birthdate</td><td id="rightHand"><%= @animal.dob != nil ? @animal.dob.strftime('%m/%d/%Y') : "" %></td></tr>
                                <tr><td id="leftHand">Age</td><td id="rightHand"><%= Time.now.year -  @animal.dob.year %></td></tr>
                                <tr><td id="leftHand">Species</td><td id="rightHand"><%= @species %> </td></tr>
                                <tr><td id="leftHand">Breed</td><td id="rightHand"><%= @animal.breed%> </td></tr>
                                <tr><td id="leftHand">Markings</td><td id="rightHand"><%= @animal.markings %> </td></tr>
                                <tr><td id="leftHand">Fixed</td><td id="rightHand"><%= @animal.isFixed %></td></tr>
                                <tr><td id="leftHand">Note</td><td id="rightHand"><%= @animal.note %></td></tr>
                        </table>
                </td>
                <td>
                        <table id="criteria">
                                <tr><td  id="leftHand">Microchip</td><td id="rightHand"><%= @animal.microchipNumber %></td></tr>
                                <tr><td  id="leftHand">Date Implanted</td><td id="rightHand"><%= @animal.dateImplanted != nil ? @animal.dateImplanted.strftime('%m/%d/%Y') : "" %></td></tr>
                                <tr><td  id="leftHand">Manufacturer</td><td id="rightHand"><%= @microchip %></td></tr>
                                <tr><td  id="leftHand">Good with other dogs</td><td id="rightHand"><%= @animal.dogs %></td></tr>
                                <tr><td  id="leftHand">Good with cats</td><td id="rightHand"><%= @animal.cats %></td></tr>
                                <tr><td  id="leftHand">Good with kids</td><td id="rightHand"><%= @animal.kids %> </td></tr>
                                <tr><td id="leftHand">Hypoallergetic</td><td id="rightHand"><%= @animal.isHypo %></td></tr>
                                <tr><td id="leftHand">Adoption Status</td><td id="rightHand"><%= @status %></td></tr>
                                <tr><td id="leftHand">Personality</td><td><ul>
				  <% @animal.personalities.each do |p| %>
				    <li><%= p.name %></li>
				  <% end %>
				</ul></td></tr>
                        </table>
                </td>
                <td id="leftHand">
                        <table id=criteria>
                                <tr><td id="rightHand"><b>Picture:</b></td></tr>
                                <tr><td><%= @animalPhoto!= nil ? image_tag(@animal.photo) : "" %></td></tr>
                        </table>
                </td>
        </tr>
        <tr>
                <td colspan=3 id="leftHand"><%= link_to "Edit", edit_animal_path(@animal)  %></td>
        </tr>   <!-- end demographic information -->
</table>
<table>
	<tr>
		<tr><td><h3>Vital Signs</h3></td></tr>
		<td>
			<div id="animal_vitals_part">
				<%= render "animal_vitals/animal_vitals" %>
			</div>
		</td>
	</tr>
</table>
<%= link_to "Back", animal_path %>