config/routes.rb
Rails.application.routes.draw do
  get "people/index"
  resource :session
  resources :passwords, param: :token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.

  root "animals#index"
  get "up" => "rails/health#show", as: :rails_health_check
  
  resources :animals #do 
#      resources :animal_vitals
#  end
  resources :people
#  resources :animal_vitals do 
#    resources :animals
#  end
  resources :vitals
  post "/animal_vitals/animal/:id",         to: "animal_vitals#create", as: "animal_vital"
  get  "/animal_vitals/new/animal/:id",     to: "animal_vitals#new",    as: "new_animal_vital"
  get  "/animal_vitals/:id",                to: "animal_vitals#edit", as: "edit_animal_vital"

get    "/animal_vitals/animal/:id", to: "animal_vitals#index",   as: "animal_vitals"
patch  "/animal_vitals/:id",        to: "animal_vitals#update",  as: "update_animal_vital"
put    "/animal_vitals/:id",        to: "animal_vitals#update"
delete "/animal_vitals/:id",        to: "animal_vitals#destroy", as: "delete_animal_vital"

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
end

app/models/animal.rb
class Animal < ApplicationRecord

  belongs_to :microchip, optional: true
  belongs_to :gender, optional: true
  belongs_to :species
  belongs_to :status, optional: true

  has_many :transfers
  has_many :vitals
  has_many :animal_personalities, dependent: :destroy
  has_many :personalities, through: :animal_personalities

  has_many :animal_vitals, dependent: :destroy
  has_many :vitals, through: :animal_vitals

  has_one_attached :photo do |attachable|
	attachable.variant :thumb, resize_to_limit: [50, 50]
  end

  validates :name, :species, presence: true
  before_save :normalize_blank_values
  
  def normalize_blank_values
    attributes.each do |column, value|
      self[column] = nil if value.blank? && value != false
    end
  end
end

app/models/animal_attribute.rb
class AnimalAttribute < ApplicationRecord
  belongs_to :animal
  belongs_to :pattribute
end

app/models/animal_personality.rb
class AnimalPersonality < ApplicationRecord
	belongs_to :animal
	belongs_to :personality
end

app/models/animal_vital.rb
class AnimalVital < ApplicationRecord
	belongs_to :animal
	belongs_to :vital


  def normalize_blank_values
    attributes.each do |column, value|
      self[column] = nil if value.blank? && value != false
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attribute.rb
class Attribute < ApplicationRecord
  has_many :animal_attributes, dependent: :destroy
  has_many :animmals, through: :animal_attributes
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :session
  delegate :user, to: :session, allow_nil: true
end

app/models/gender.rb
class Gender < ApplicationRecord
  has_many :animals
end

app/models/microchip.rb
class Microchip < ApplicationRecord
	has_many :animals
end

app/models/microchip_type.rb
class MicrochipType < ApplicationRecord
	has_many :animal
end

app/models/person.rb
class Person < ApplicationRecord

  def normalize_blank_values
    attributes.each do |column, value|
      self[column] = nil if value.blank? && value != false
    end
  end

end

app/models/personality.rb
class Personality < ApplicationRecord
  has_many :animal_personalities, dependent: :destroy
  has_many :animals, through: :animal_personality

end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
end

app/models/species.rb
class Species < ApplicationRecord
	has_many :animals
	has_many :vitals
end

app/models/status.rb
class Status < ApplicationRecord
	has_many :animals
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :sessions, dependent: :destroy

  normalizes :email_address, with: ->(e) { e.strip.downcase }
end

app/models/vital.rb
class Vital < ApplicationRecord
  has_many :animal_vitals, dependent: :destroy
  has_many :animals, through: :animal_vital
  belongs_to :species, optional: true
end

app/controllers/vitals_controller.rb
class VitalsController < ApplicationController
  allow_unauthenticated_access only: %i[ index show ]
  before_action :set_vital, only: %i[ show edit update destroy ]

 def index
        @vitals = Vital.all
 end

  def show
    @pageName = "View Vital"
  end

  def new
    @pageName = "New Vital"
    @vital = Vital.new
  end

  def create
    @pageName = "Add Vital"
    @vital = Vital.new(vital_params)
    if @vital.save!
      redirect_to @vital
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @pageName = "Edit Vital"
  end

  def update
#    Rails.error.subscribe(ErrorSubscriber.new)
    if @vital.update!(vital_params)
      redirect_to vitals_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
      @vital.destroy
      redirect_to vitals_path
  end

  private
    def set_vital
      @vital = Vital.find(params[:id])
    end

    def vital_params
      params.expect(vital: [ :id, :name, :short_name, :hi,  :low, :species_id, :units ])
    end
end

app/helpers/animal_vitals_helper.rb
module AnimalVitalsHelper
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/vital_helper.rb
module VitalHelper
end

app/helpers/vitals_helper.rb
module VitalsHelper
end

app/views/vitals/_form.html.erb
<%= form_with model: @vital do |form| %>
  <div>
<table id=criteria>
	<tr><td><%= form.label :name %></td><td><%= form.text_field :name %></tr>
	<tr><td><%= form.label :short_name %></td><td><%= form.text_field :short_name  %></tr>
	<tr>
		<td style="text-align: right;"><b>Species*</b> </td>
		<td style="text-align: left;" ><%= form.collection_select(:species_id, Species.all, :id, :name,   include_blank: 'All', selected: @vital.species_id) %></td>

	</tr>
	<tr><td><%= form.label :low %></td><td><%= form.number_field :low, step: :any  %></tr>
	<tr><td><%= form.label :high %></td><td><%= form.number_field :hi, step: :any  %></tr>
	<tr><td><%= form.label :units %></td><td><%= form.text_field :units  %></tr>

	</table>


  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/vitals/edit.html.erb
<h1>Edit Vital</h1>

<%= render "form", vital: @vital %>
<%= button_to "Delete", @vital, method: :delete, data: { turbo_confirm: "Are you sure?" } %>
<%= link_to "Cancel", vitals_path %>

app/views/vitals/index.html.erb
<h1>vitals</h1>

<div id="vitals">
	<table>

		<th>Id</th>
		<th>Name</th>
		<th>Short Name</th>
		<th>Species</th>
		<th>Low</th>
		<th>High</th>
		<th>units</th>
		<th>Created At</th>
		<th>Updated At</th>
		<th></th>
	<% @vitals.each do |vital| %>
		<tr>
			<td><%= vital.id  %></td>
                        <td><%= vital.name  %></td>
                        <td><%= vital.short_name  %></td>
                        <td><%= vital.species_id != nil ? Species.find(vital.species_id).name : "" %></td>
			<td><%= vital.low  %></td>
			<td><%= vital.hi  %></td>
			<td><%= vital.units  %></td>
			<td><%= vital.created_at  %></td>
			<td><%= vital.updated_at  %></td>
			<td><%= link_to "Edit", edit_vital_path(vital)  %></td>
		</tr>
	<% end %>
	</table>
	<%= link_to "New Vital", new_vital_path %>
</div>

<%= link_to "Back" %>

app/views/vitals/new.html.erb
<h1>New Vital</h1>

<%= render "form", vital: @vital %>
<%= link_to "Cancel", vitals_path %>