config/routes.rb
Rails.application.routes.draw do
  get "people/index"
  resource :session
  resources :passwords, param: :token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.

  root "animals#index"
  get "up" => "rails/health#show", as: :rails_health_check
  
  resources :animals #do 
#      resources :animal_vitals
#  end
  resources :people
#  resources :animal_vitals do 
#    resources :animals
#  end
  resources :vitals
  post "/animal_vitals/animal/:id",         to: "animal_vitals#create", as: "animal_vital"
  get  "/animal_vitals/new/animal/:id",     to: "animal_vitals#new",    as: "new_animal_vital"
  get  "/animal_vitals/:id",                to: "animal_vitals#edit", as: "edit_animal_vital"

get    "/animal_vitals/animal/:id", to: "animal_vitals#index",   as: "animal_vitals"
patch  "/animal_vitals/:id",        to: "animal_vitals#update",  as: "update_animal_vital"
put    "/animal_vitals/:id",        to: "animal_vitals#update"
delete "/animal_vitals/:id",        to: "animal_vitals#destroy", as: "delete_animal_vital"

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
end

app/models/animal.rb
class Animal < ApplicationRecord

  belongs_to :microchip, optional: true
  belongs_to :gender, optional: true
  belongs_to :species
  belongs_to :status, optional: true

  has_many :transfers
  has_many :vitals
  has_many :animal_personalities, dependent: :destroy
  has_many :personalities, through: :animal_personalities

  has_many :animal_vitals, dependent: :destroy
  has_many :vitals, through: :animal_vitals

  has_one_attached :photo do |attachable|
	attachable.variant :thumb, resize_to_limit: [50, 50]
  end

  validates :name, :species, presence: true
  before_save :normalize_blank_values
  
  def normalize_blank_values
    attributes.each do |column, value|
      self[column] = nil if value.blank? && value != false
    end
  end
end

app/models/animal_attribute.rb
class AnimalAttribute < ApplicationRecord
  belongs_to :animal
  belongs_to :pattribute
end

app/models/animal_personality.rb
class AnimalPersonality < ApplicationRecord
	belongs_to :animal
	belongs_to :personality
end

app/models/animal_vital.rb
class AnimalVital < ApplicationRecord
	belongs_to :animal
	belongs_to :vital


  def normalize_blank_values
    attributes.each do |column, value|
      self[column] = nil if value.blank? && value != false
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attribute.rb
class Attribute < ApplicationRecord
  has_many :animal_attributes, dependent: :destroy
  has_many :animmals, through: :animal_attributes
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :session
  delegate :user, to: :session, allow_nil: true
end

app/models/gender.rb
class Gender < ApplicationRecord
  has_many :animals
end

app/models/microchip.rb
class Microchip < ApplicationRecord
	has_many :animals
end

app/models/microchip_type.rb
class MicrochipType < ApplicationRecord
	has_many :animal
end

app/models/person.rb
class Person < ApplicationRecord

  def normalize_blank_values
    attributes.each do |column, value|
      self[column] = nil if value.blank? && value != false
    end
  end

end

app/models/personality.rb
class Personality < ApplicationRecord
  has_many :animal_personalities, dependent: :destroy
  has_many :animals, through: :animal_personality

end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
end

app/models/species.rb
class Species < ApplicationRecord
	has_many :animals
	has_many :vitals
end

app/models/status.rb
class Status < ApplicationRecord
	has_many :animals
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :sessions, dependent: :destroy

  normalizes :email_address, with: ->(e) { e.strip.downcase }
end

app/models/vital.rb
class Vital < ApplicationRecord
  has_many :animal_vitals, dependent: :destroy
  has_many :animals, through: :animal_vital
  belongs_to :species, optional: true
end

app/controllers/animal_vitals_controller.rb
class AnimalVitalsController < ApplicationController
 allow_unauthenticated_access only: %i[ index show ]
  def index
    @animal = Animal.find(params[:id])
    @animal_vitals = AnimalVital.where(animal_id: @animal.id)
  end

  def show
    @pageName = "View Vitals"
    @animal = Animals.find!(params[:id])
    @animal_vitals = Animal.find(@animal.animal_id).name
  end

  def new
    @pageName = "New Vital"
    @animal = Animal.find(params[:id])
    @animal_vital = AnimalVital.new
    @vitals = Vital.where(species_id: @animal.species_id).or(Vital.where(species_id: nil))
  end

  def create
    @formRet = new_animal_vital_path
    @av = AnimalVital.new(animal_vital_params)
    if @av.save!
      redirect_to @av.animal
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @pageName = "Edit Vital"
    @formRet = edit_animal_vital_path(params[:id])
    @animal_vital = AnimalVital.find(params[:id])
    @animal = Animal.find(@animal_vital.animal_id)
    @vitals = Vital.where(species_id: @animal.species_id).or(Vital.where(species_id: nil))
  end

  def update
#    Rails.error.subscribe(ErrorSubscriber.new)
    @animal_vital = AnimalVital.find(params[:id])

    if @animal_vital.update!(animal_vital_params)
      @animal = Animal.find(@animal_vital.animal_id)
      redirect_to @animal
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
      @animal_vital = AnimalVital.find(params[:id])
      @animal_id = @animal_vital.animal_id
      @animal_vital.destroy
      redirect_to animal_path(@animal_id)
  end

  private

    def animal_vital_params
      params.expect(animal_vital: [ :animal_id, :vital_id, :note, :value, :dt  ])
    end
end

app/helpers/animal_vitals_helper.rb
module AnimalVitalsHelper
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/vital_helper.rb
module VitalHelper
end

app/helpers/vitals_helper.rb
module VitalsHelper
end

app/views/animal_vitals/_animal_vitals.html.erb
<div id="animal_vitals">
	<table id="tabular">
		<th>Date / Time</th>
		<th>Vital Name</th>
		<th>Value</th>
		<th>Flag</th>
		<th>Range</th>
		<th>Note</th>
		<th></th>
		<th></th>
		<% @animal_vitals.each do |animal_vital| %>
			<% @vital = Vital.find(animal_vital.vital_id) %>	
			<tr>
				<td><%= animal_vital.dt.strftime('%m/%d/%Y') %>
				<td><%= @vital.short_name %></td>
				<td><%= raw @vital.low != nil ? (animal_vital.value < @vital.low ? "<font color=\"blue\" >"+animal_vital.value.to_s+" "+@vital.units+"</font>" : (animal_vital.value > @vital.hi ? "<font color='red'>"+animal_vital.value.to_s+" "+@vital.units+"</font>" : animal_vital.value )) : animal_vital.value %> </td>
 				<td><%= raw @vital.low != nil ? (animal_vital.value < @vital.low ? "<font color='blue'>L</font>" : (animal_vital.value > @vital.hi ? "<font color='red'>H</font>" : "")) : "" %> </td>
				<td><%= @vital.low %> - <%= @vital.hi %></td>
				<td><%= animal_vital.note %></td>
				<td><%= link_to "Edit", edit_animal_vital_path(animal_vital)  %></td>
				<td><%= button_to "Delete", delete_animal_vital_path(animal_vital.id), method: :delete, data: { turbo_confirm: "Are you sure?" } %></td>

			</tr>
		<% end %>
	</table>
	<%= link_to "Add New", new_animal_vital_path(@animal) %>
</div>

app/views/animal_vitals/_form.html.erb
<%= form_with url: @formRet, model: @animal_vital do |form| %>
  <div>
 <%= form.hidden_field :animal_id, value: @animal.id %>
<table id=criteria>
                <tr>
                        <td>
                                <table>
                                        <tr>
                                                <td><b>Vital Sign Name:</b></td>
                                                <td><%= form.collection_select(:vital_id, @vitals, :id, :name, selected: @animal_vital.vital_id) %></td>

                                        </tr>
                                        <tr>
						<tr><td><%= form.label :value, "Value" %></td><td><%= form.text_field :value %></tr>
						<select id="weightUnit" name="weightUnit" hidden><option value=1>lbs</option><option value=2.205>kgs</option></select>
                                        </tr>
						<tr><td><%= form.label :dt, "Date" %></td><td><%= form.date_field :dt, value: Date.today %></tr>
						<tr><td><%= form.label :tm, "Time" %></td><td><%= form.time_field :tm, value: Time.now %></tr>
                                        <tr>
                                        </tr>
						<tr><td><%= form.label :note, "Note" %></td><td><%= form.text_area :note, rows: 10, cols: 50 %></tr>
                                        <tr>
                                                <td colspan="2"> 
							<%= form.submit %>
                                                </td>
                                        </tr>
                                </table>
                        </td>
                        <td>
                                <table> <!-- first column of demographic information -->
                                        <tr><td colspan=2></td><b>Vital Sign Information for:</b></td></tr>
					<tr><td>Birthdate</td><td><%= @animal.dob != nil ? @animal.dob.strftime('%m/%d/%Y') : "" %></td></tr>
					<tr><td>Age</td><td><%= Time.now.year -  @animal.dob.year %></td></tr>
                                        <tr><td style="text-align: left;" colspan="2"><%= link_to "Back to " + @animal.name, animal_path %></td></tr>
                                        </td></tr>
                                </table>
                        </td>
                </tr>
</table>

  </div>

<% end %>

app/views/animal_vitals/edit.html.erb
<%= render "form", url: update_animal_vital_path,  animal_vital: @animal_vital %>
<%= button_to "Delete", @animal_vital, method: :delete, data: { turbo_confirm: "Are you sure?" } %>
<%= link_to "Cancel", @animal %>

app/views/animal_vitals/new.html.erb
<h1>New Vital for <%= link_to @animal.name, @animal %></h1>

<%= render "form", animal_vital: @animal_vital %>
<%= link_to "Cancel", @animal %>

app/views/animal_vitals/show.html.erb
<h1>Vitals for <%= link_to @animal.name, @animal %></h1>

<table id=tabular>
<?php 
        foreach ($vitalList as $vital) {
?>
        <tr >
                <td colspan="5">
                        <font color="purple"><b><a href="viewVitals.php?animalID=<?= $animalID ?>&vitalSignTypeID=<?= $vital['vitalSignTypeID'] ?>"><?= $vital['vitalSignTypeName'] ?></b></font>
                </td>
        </tr>
        <tr>
          <th width="150px">Date</th>
          <th width="150px">Value</th>
          <th width="100px">Range</th>
          <th>Note</th>
          <th width="100px">&nbsp;</th>
        </tr>
        <?php
                $sql = "select * FROM VitalSign WHERE animalID=$animalID and vitalSignTypeID=".$vital['vitalSignTypeID'] . " ORDER BY vitalDateTime DESC";
                $result = $mysqli->query($sql);
                if ($mysqli->errno)   errorPage($mysqli->errno, $mysqli->error, $sql);
                while ($row=$result->fetch_array()) {
        ?>
        <tr>
                <td><?= MySQL2Date($row['vitalDateTime']) ?> <?= MySQL2Time($row['vitalDateTime']) ?>&nbsp;</td>
                <td><font color="<?php
                        $modifier='';
                        if (($vital['low']+$vital['low'])>0) {
                                if ($row['vitalValue'] < $vital['low']) {
                                        echo "blue";
                                        $modifier=" L";
                                } else if ($row['vitalValue'] > $vital['hi']) {
                                        echo "red";
                                        $modifier=" H";
                                } else echo "black";
                        }
                ?>"><?= $row['vitalValue']." ".$vital['units'].$modifier ?>&nbsp;</font></td>
                <td><?= $vital['range'] ?>&nbsp;</td>
                <td style="white-space: pre-line;"><?= $row['note'] ?>&nbsp;</td>
                <td>
                        <a href="<?= "viewVitals.php?animalID=$animalID&vitalSignTypeID=".$vital['vitalSignTypeID']."&vitalDateTime=".$row['vitalDateTime']."&action=edit" ?>">Edit</a> / 
                        <a href="<?= "viewVitals.php?animalID=$animalID&vitalSignTypeID=".$vital['vitalSignTypeID']."&vitalDateTime=".$row['vitalDateTime']."&action=delete" ?>"
                                onclick="return confirm('Are you sure you want to delete this record?  This action can not be undone.');">Delete</a>
                </td>
        </tr>
        <?php
                }
        ?>
        <tr><td colspan="5">&nbsp;</td></tr> <!--  Blank row -->
<?php
        }
?>
</table>

<table>
<tr><td><b>Key</b></td></tr>
<tr><td><font color="blue">Blue:</font> Too Low</td></tr>
<tr><td><font color="red">Red: </font> Too High</td></tr>
<tr><td><font color="black">Black: </font> Within Range</td></tr>
</table>


<%= link_to "Add Vital", new_animal_vital_path %>
<%= link_to "Back", animal_path %>