config/routes.rb
Rails.application.routes.draw do
  get "people/index"
  resource :session
  resources :passwords, param: :token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.

  root "animals#index"
  get "up" => "rails/health#show", as: :rails_health_check
  
  resources :animals #do 
#      resources :animal_vitals
#  end
  resources :people
#  resources :animal_vitals do 
#    resources :animals
#  end
  resources :vitals
  post "/animal_vitals/animal/:id",         to: "animal_vitals#create", as: "animal_vital"
  get  "/animal_vitals/new/animal/:id",     to: "animal_vitals#new",    as: "new_animal_vital"
  get  "/animal_vitals/:id",                to: "animal_vitals#edit", as: "edit_animal_vital"

get    "/animal_vitals/animal/:id", to: "animal_vitals#index",   as: "animal_vitals"
patch  "/animal_vitals/:id",        to: "animal_vitals#update",  as: "update_animal_vital"
put    "/animal_vitals/:id",        to: "animal_vitals#update"
delete "/animal_vitals/:id",        to: "animal_vitals#destroy", as: "delete_animal_vital"

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
end

app/models/animal.rb
class Animal < ApplicationRecord

  belongs_to :microchip, optional: true
  belongs_to :gender, optional: true
  belongs_to :species
  belongs_to :status, optional: true

  has_many :transfers
  has_many :vitals
  has_many :animal_personalities, dependent: :destroy
  has_many :personalities, through: :animal_personalities

  has_many :animal_vitals, dependent: :destroy
  has_many :vitals, through: :animal_vitals

  has_one_attached :photo do |attachable|
	attachable.variant :thumb, resize_to_limit: [50, 50]
  end

  validates :name, :species, presence: true
  before_save :normalize_blank_values
  
  def normalize_blank_values
    attributes.each do |column, value|
      self[column] = nil if value.blank? && value != false
    end
  end
end

app/models/animal_attribute.rb
class AnimalAttribute < ApplicationRecord
  belongs_to :animal
  belongs_to :pattribute
end

app/models/animal_personality.rb
class AnimalPersonality < ApplicationRecord
	belongs_to :animal
	belongs_to :personality
end

app/models/animal_vital.rb
class AnimalVital < ApplicationRecord
	belongs_to :animal
	belongs_to :vital


  def normalize_blank_values
    attributes.each do |column, value|
      self[column] = nil if value.blank? && value != false
    end
  end

end

app/models/attribute.rb
class Attribute < ApplicationRecord
  has_many :animal_attributes, dependent: :destroy
  has_many :animmals, through: :animal_attributes
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :session
  delegate :user, to: :session, allow_nil: true
end

app/models/gender.rb
class Gender < ApplicationRecord
  has_many :animals
end

app/models/microchip.rb
class Microchip < ApplicationRecord
	has_many :animals
end

app/models/microchip_type.rb
class MicrochipType < ApplicationRecord
	has_many :animal
end

app/models/person.rb
class Person < ApplicationRecord

  def normalize_blank_values
    attributes.each do |column, value|
      self[column] = nil if value.blank? && value != false
    end
  end

end

app/models/personality.rb
class Personality < ApplicationRecord
  has_many :animal_personalities, dependent: :destroy
  has_many :animals, through: :animal_personality

end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
end

app/models/species.rb
class Species < ApplicationRecord
	has_many :animals
	has_many :vitals
end

app/models/status.rb
class Status < ApplicationRecord
	has_many :animals
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :sessions, dependent: :destroy

  normalizes :email_address, with: ->(e) { e.strip.downcase }
end

app/models/vital.rb
class Vital < ApplicationRecord
  has_many :animal_vitals, dependent: :destroy
  has_many :animals, through: :animal_vital
  belongs_to :species, optional: true
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/vital_helper.rb
module VitalHelper
end

app/helpers/vitals_helper.rb
module VitalsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "PetTrax" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "pettrax" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>



       <table>
                <tr>
                        <!-- Pixie Icon -->
                        <td><%= image_tag("AnimalTraxLogo.png", size: '100x100') %></td>

                        <!-- Banner title -->
                        <td style="vertical-align: bottom;">
                        <font size=6><b><center>PetTrax Animal Tracing System</center></b></font>
                        <p><font size=5><%= @pageName %></font></b>
                        </td>
                        <td style="text-align: right;">
				<%= Current.user.email_address if authenticated? %><br>
				<%= link_to "Log out", session_path, method: :delete if authenticated? %>
                        </td>
                </tr>

                <tr> <!-- Row 2, column 1: Sidebar menu -->
                        <td id="sidebar">
                                <font size=4>
                                        <nav>
                                                <ul>
                                                        <li><%= link_to "Find Animals", animals_path %></li>
                                                        <li><%= link_to "Add Animal", new_animal_path %></li>        
                                                        <li><%= link_to "Find People", people_path %></li>
                                                        <li><%= link_to "Add Person", new_person_path %></li>        
                                                </ul>
                                        </nav>
                                </font>
                        </td>
                        <td style="background-color: white;" colspan=2>
                                <table border="1" style="width: 100%" ><tr><td>

    <main>
      <%= yield %>
    </main>
		</td></tr>
	</table>
  </body>
  </footer>
  <footer>
</html>